project_name: terraform-provider-harbor
before:
  hooks:
    - go mod download

builds:
  - binary: "{{ .ProjectName }}_v{{ .Version }}"
    env:
    - CGO_ENABLED=0
    goos:
    - windows
    - darwin
    - linux
    ignore:
    - goarch: 386

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

checksum:
   name_template: "{{ .ProjectName }}_{{ .Tag }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
