before:
  hooks:
    - go mod download
builds:
- id: terraform-provider-harbor
  binary: terraform-provider-harbor
  env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  ignore:
  - goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
