// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRepositoriesRepoNameTagsTagReader is a Reader for the DeleteRepositoriesRepoNameTagsTag structure.
type DeleteRepositoriesRepoNameTagsTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRepositoriesRepoNameTagsTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRepositoriesRepoNameTagsTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRepositoriesRepoNameTagsTagBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteRepositoriesRepoNameTagsTagUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteRepositoriesRepoNameTagsTagForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRepositoriesRepoNameTagsTagNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRepositoriesRepoNameTagsTagOK creates a DeleteRepositoriesRepoNameTagsTagOK with default headers values
func NewDeleteRepositoriesRepoNameTagsTagOK() *DeleteRepositoriesRepoNameTagsTagOK {
	return &DeleteRepositoriesRepoNameTagsTagOK{}
}

/*DeleteRepositoriesRepoNameTagsTagOK handles this case with default header values.

Delete tag successfully.
*/
type DeleteRepositoriesRepoNameTagsTagOK struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagOK) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}][%d] deleteRepositoriesRepoNameTagsTagOK ", 200)
}

func (o *DeleteRepositoriesRepoNameTagsTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagBadRequest creates a DeleteRepositoriesRepoNameTagsTagBadRequest with default headers values
func NewDeleteRepositoriesRepoNameTagsTagBadRequest() *DeleteRepositoriesRepoNameTagsTagBadRequest {
	return &DeleteRepositoriesRepoNameTagsTagBadRequest{}
}

/*DeleteRepositoriesRepoNameTagsTagBadRequest handles this case with default header values.

Invalid repo_name.
*/
type DeleteRepositoriesRepoNameTagsTagBadRequest struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}][%d] deleteRepositoriesRepoNameTagsTagBadRequest ", 400)
}

func (o *DeleteRepositoriesRepoNameTagsTagBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagUnauthorized creates a DeleteRepositoriesRepoNameTagsTagUnauthorized with default headers values
func NewDeleteRepositoriesRepoNameTagsTagUnauthorized() *DeleteRepositoriesRepoNameTagsTagUnauthorized {
	return &DeleteRepositoriesRepoNameTagsTagUnauthorized{}
}

/*DeleteRepositoriesRepoNameTagsTagUnauthorized handles this case with default header values.

Unauthorized.
*/
type DeleteRepositoriesRepoNameTagsTagUnauthorized struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}][%d] deleteRepositoriesRepoNameTagsTagUnauthorized ", 401)
}

func (o *DeleteRepositoriesRepoNameTagsTagUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagForbidden creates a DeleteRepositoriesRepoNameTagsTagForbidden with default headers values
func NewDeleteRepositoriesRepoNameTagsTagForbidden() *DeleteRepositoriesRepoNameTagsTagForbidden {
	return &DeleteRepositoriesRepoNameTagsTagForbidden{}
}

/*DeleteRepositoriesRepoNameTagsTagForbidden handles this case with default header values.

Forbidden.
*/
type DeleteRepositoriesRepoNameTagsTagForbidden struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagForbidden) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}][%d] deleteRepositoriesRepoNameTagsTagForbidden ", 403)
}

func (o *DeleteRepositoriesRepoNameTagsTagForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagNotFound creates a DeleteRepositoriesRepoNameTagsTagNotFound with default headers values
func NewDeleteRepositoriesRepoNameTagsTagNotFound() *DeleteRepositoriesRepoNameTagsTagNotFound {
	return &DeleteRepositoriesRepoNameTagsTagNotFound{}
}

/*DeleteRepositoriesRepoNameTagsTagNotFound handles this case with default header values.

Repository or tag not found.
*/
type DeleteRepositoriesRepoNameTagsTagNotFound struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagNotFound) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}][%d] deleteRepositoriesRepoNameTagsTagNotFound ", 404)
}

func (o *DeleteRepositoriesRepoNameTagsTagNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
