// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRepositoriesRepoNameTagsTagParams creates a new DeleteRepositoriesRepoNameTagsTagParams object
// with the default values initialized.
func NewDeleteRepositoriesRepoNameTagsTagParams() *DeleteRepositoriesRepoNameTagsTagParams {
	var ()
	return &DeleteRepositoriesRepoNameTagsTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRepositoriesRepoNameTagsTagParamsWithTimeout creates a new DeleteRepositoriesRepoNameTagsTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRepositoriesRepoNameTagsTagParamsWithTimeout(timeout time.Duration) *DeleteRepositoriesRepoNameTagsTagParams {
	var ()
	return &DeleteRepositoriesRepoNameTagsTagParams{

		timeout: timeout,
	}
}

// NewDeleteRepositoriesRepoNameTagsTagParamsWithContext creates a new DeleteRepositoriesRepoNameTagsTagParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRepositoriesRepoNameTagsTagParamsWithContext(ctx context.Context) *DeleteRepositoriesRepoNameTagsTagParams {
	var ()
	return &DeleteRepositoriesRepoNameTagsTagParams{

		Context: ctx,
	}
}

// NewDeleteRepositoriesRepoNameTagsTagParamsWithHTTPClient creates a new DeleteRepositoriesRepoNameTagsTagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRepositoriesRepoNameTagsTagParamsWithHTTPClient(client *http.Client) *DeleteRepositoriesRepoNameTagsTagParams {
	var ()
	return &DeleteRepositoriesRepoNameTagsTagParams{
		HTTPClient: client,
	}
}

/*DeleteRepositoriesRepoNameTagsTagParams contains all the parameters to send to the API endpoint
for the delete repositories repo name tags tag operation typically these are written to a http.Request
*/
type DeleteRepositoriesRepoNameTagsTagParams struct {

	/*RepoName
	  The name of repository which will be deleted.

	*/
	RepoName string
	/*Tag
	  Tag of a repository.

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) WithTimeout(timeout time.Duration) *DeleteRepositoriesRepoNameTagsTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) WithContext(ctx context.Context) *DeleteRepositoriesRepoNameTagsTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) WithHTTPClient(client *http.Client) *DeleteRepositoriesRepoNameTagsTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoName adds the repoName to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) WithRepoName(repoName string) *DeleteRepositoriesRepoNameTagsTagParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) WithTag(tag string) *DeleteRepositoriesRepoNameTagsTagParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the delete repositories repo name tags tag params
func (o *DeleteRepositoriesRepoNameTagsTagParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRepositoriesRepoNameTagsTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
