// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRepositoriesRepoNameLabelsLabelIDParams creates a new DeleteRepositoriesRepoNameLabelsLabelIDParams object
// with the default values initialized.
func NewDeleteRepositoriesRepoNameLabelsLabelIDParams() *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	var ()
	return &DeleteRepositoriesRepoNameLabelsLabelIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRepositoriesRepoNameLabelsLabelIDParamsWithTimeout creates a new DeleteRepositoriesRepoNameLabelsLabelIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRepositoriesRepoNameLabelsLabelIDParamsWithTimeout(timeout time.Duration) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	var ()
	return &DeleteRepositoriesRepoNameLabelsLabelIDParams{

		timeout: timeout,
	}
}

// NewDeleteRepositoriesRepoNameLabelsLabelIDParamsWithContext creates a new DeleteRepositoriesRepoNameLabelsLabelIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRepositoriesRepoNameLabelsLabelIDParamsWithContext(ctx context.Context) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	var ()
	return &DeleteRepositoriesRepoNameLabelsLabelIDParams{

		Context: ctx,
	}
}

// NewDeleteRepositoriesRepoNameLabelsLabelIDParamsWithHTTPClient creates a new DeleteRepositoriesRepoNameLabelsLabelIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRepositoriesRepoNameLabelsLabelIDParamsWithHTTPClient(client *http.Client) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	var ()
	return &DeleteRepositoriesRepoNameLabelsLabelIDParams{
		HTTPClient: client,
	}
}

/*DeleteRepositoriesRepoNameLabelsLabelIDParams contains all the parameters to send to the API endpoint
for the delete repositories repo name labels label ID operation typically these are written to a http.Request
*/
type DeleteRepositoriesRepoNameLabelsLabelIDParams struct {

	/*LabelID
	  The ID of label.

	*/
	LabelID int64
	/*RepoName
	  The name of repository.

	*/
	RepoName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) WithTimeout(timeout time.Duration) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) WithContext(ctx context.Context) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) WithHTTPClient(client *http.Client) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLabelID adds the labelID to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) WithLabelID(labelID int64) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	o.SetLabelID(labelID)
	return o
}

// SetLabelID adds the labelId to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) SetLabelID(labelID int64) {
	o.LabelID = labelID
}

// WithRepoName adds the repoName to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) WithRepoName(repoName string) *DeleteRepositoriesRepoNameLabelsLabelIDParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the delete repositories repo name labels label ID params
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRepositoriesRepoNameLabelsLabelIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param label_id
	if err := r.SetPathParam("label_id", swag.FormatInt64(o.LabelID)); err != nil {
		return err
	}

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
