// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRepositoriesRepoNameTagsTagLabelsLabelIDReader is a Reader for the DeleteRepositoriesRepoNameTagsTagLabelsLabelID structure.
type DeleteRepositoriesRepoNameTagsTagLabelsLabelIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK creates a DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK with default headers values
func NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK() *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK {
	return &DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK{}
}

/*DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK handles this case with default header values.

Successfully.
*/
type DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}/labels/{label_id}][%d] deleteRepositoriesRepoNameTagsTagLabelsLabelIdOK ", 200)
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized creates a DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized with default headers values
func NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized() *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized {
	return &DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized{}
}

/*DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized handles this case with default header values.

Unauthorized.
*/
type DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}/labels/{label_id}][%d] deleteRepositoriesRepoNameTagsTagLabelsLabelIdUnauthorized ", 401)
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden creates a DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden with default headers values
func NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden() *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden {
	return &DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden{}
}

/*DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden handles this case with default header values.

Forbidden. User should have write permisson for the image to perform the action.
*/
type DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}/labels/{label_id}][%d] deleteRepositoriesRepoNameTagsTagLabelsLabelIdForbidden ", 403)
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound creates a DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound with default headers values
func NewDeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound() *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound {
	return &DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound{}
}

/*DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound handles this case with default header values.

Resource not found.
*/
type DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound struct {
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /repositories/{repo_name}/tags/{tag}/labels/{label_id}][%d] deleteRepositoriesRepoNameTagsTagLabelsLabelIdNotFound ", 404)
}

func (o *DeleteRepositoriesRepoNameTagsTagLabelsLabelIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
