// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sandhose/terraform-provider-harbor/api/models"
)

// GetLabelsIDResourcesReader is a Reader for the GetLabelsIDResources structure.
type GetLabelsIDResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLabelsIDResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLabelsIDResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetLabelsIDResourcesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetLabelsIDResourcesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetLabelsIDResourcesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetLabelsIDResourcesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLabelsIDResourcesOK creates a GetLabelsIDResourcesOK with default headers values
func NewGetLabelsIDResourcesOK() *GetLabelsIDResourcesOK {
	return &GetLabelsIDResourcesOK{}
}

/*GetLabelsIDResourcesOK handles this case with default header values.

Get successfully.
*/
type GetLabelsIDResourcesOK struct {
	Payload *models.Resource
}

func (o *GetLabelsIDResourcesOK) Error() string {
	return fmt.Sprintf("[GET /labels/{id}/resources][%d] getLabelsIdResourcesOK  %+v", 200, o.Payload)
}

func (o *GetLabelsIDResourcesOK) GetPayload() *models.Resource {
	return o.Payload
}

func (o *GetLabelsIDResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Resource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLabelsIDResourcesUnauthorized creates a GetLabelsIDResourcesUnauthorized with default headers values
func NewGetLabelsIDResourcesUnauthorized() *GetLabelsIDResourcesUnauthorized {
	return &GetLabelsIDResourcesUnauthorized{}
}

/*GetLabelsIDResourcesUnauthorized handles this case with default header values.

User need to log in first.
*/
type GetLabelsIDResourcesUnauthorized struct {
}

func (o *GetLabelsIDResourcesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /labels/{id}/resources][%d] getLabelsIdResourcesUnauthorized ", 401)
}

func (o *GetLabelsIDResourcesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLabelsIDResourcesForbidden creates a GetLabelsIDResourcesForbidden with default headers values
func NewGetLabelsIDResourcesForbidden() *GetLabelsIDResourcesForbidden {
	return &GetLabelsIDResourcesForbidden{}
}

/*GetLabelsIDResourcesForbidden handles this case with default header values.

Forbidden.
*/
type GetLabelsIDResourcesForbidden struct {
}

func (o *GetLabelsIDResourcesForbidden) Error() string {
	return fmt.Sprintf("[GET /labels/{id}/resources][%d] getLabelsIdResourcesForbidden ", 403)
}

func (o *GetLabelsIDResourcesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLabelsIDResourcesNotFound creates a GetLabelsIDResourcesNotFound with default headers values
func NewGetLabelsIDResourcesNotFound() *GetLabelsIDResourcesNotFound {
	return &GetLabelsIDResourcesNotFound{}
}

/*GetLabelsIDResourcesNotFound handles this case with default header values.

The resource does not exist.
*/
type GetLabelsIDResourcesNotFound struct {
}

func (o *GetLabelsIDResourcesNotFound) Error() string {
	return fmt.Sprintf("[GET /labels/{id}/resources][%d] getLabelsIdResourcesNotFound ", 404)
}

func (o *GetLabelsIDResourcesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetLabelsIDResourcesInternalServerError creates a GetLabelsIDResourcesInternalServerError with default headers values
func NewGetLabelsIDResourcesInternalServerError() *GetLabelsIDResourcesInternalServerError {
	return &GetLabelsIDResourcesInternalServerError{}
}

/*GetLabelsIDResourcesInternalServerError handles this case with default header values.

Unexpected internal errors.
*/
type GetLabelsIDResourcesInternalServerError struct {
}

func (o *GetLabelsIDResourcesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /labels/{id}/resources][%d] getLabelsIdResourcesInternalServerError ", 500)
}

func (o *GetLabelsIDResourcesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
