// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoriesTopParams creates a new GetRepositoriesTopParams object
// with the default values initialized.
func NewGetRepositoriesTopParams() *GetRepositoriesTopParams {
	var ()
	return &GetRepositoriesTopParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesTopParamsWithTimeout creates a new GetRepositoriesTopParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesTopParamsWithTimeout(timeout time.Duration) *GetRepositoriesTopParams {
	var ()
	return &GetRepositoriesTopParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesTopParamsWithContext creates a new GetRepositoriesTopParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesTopParamsWithContext(ctx context.Context) *GetRepositoriesTopParams {
	var ()
	return &GetRepositoriesTopParams{

		Context: ctx,
	}
}

// NewGetRepositoriesTopParamsWithHTTPClient creates a new GetRepositoriesTopParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesTopParamsWithHTTPClient(client *http.Client) *GetRepositoriesTopParams {
	var ()
	return &GetRepositoriesTopParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesTopParams contains all the parameters to send to the API endpoint
for the get repositories top operation typically these are written to a http.Request
*/
type GetRepositoriesTopParams struct {

	/*Count
	  The number of the requested public repositories, default is 10 if not provided.

	*/
	Count *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories top params
func (o *GetRepositoriesTopParams) WithTimeout(timeout time.Duration) *GetRepositoriesTopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories top params
func (o *GetRepositoriesTopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories top params
func (o *GetRepositoriesTopParams) WithContext(ctx context.Context) *GetRepositoriesTopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories top params
func (o *GetRepositoriesTopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories top params
func (o *GetRepositoriesTopParams) WithHTTPClient(client *http.Client) *GetRepositoriesTopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories top params
func (o *GetRepositoriesTopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCount adds the count to the get repositories top params
func (o *GetRepositoriesTopParams) WithCount(count *int32) *GetRepositoriesTopParams {
	o.SetCount(count)
	return o
}

// SetCount adds the count to the get repositories top params
func (o *GetRepositoriesTopParams) SetCount(count *int32) {
	o.Count = count
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesTopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Count != nil {

		// query param count
		var qrCount int32
		if o.Count != nil {
			qrCount = *o.Count
		}
		qCount := swag.FormatInt32(qrCount)
		if qCount != "" {
			if err := r.SetQueryParam("count", qCount); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
