// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sandhose/terraform-provider-harbor/api/models"
)

// GetRepositoriesRepoNameSignaturesReader is a Reader for the GetRepositoriesRepoNameSignatures structure.
type GetRepositoriesRepoNameSignaturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesRepoNameSignaturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepositoriesRepoNameSignaturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetRepositoriesRepoNameSignaturesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRepositoriesRepoNameSignaturesOK creates a GetRepositoriesRepoNameSignaturesOK with default headers values
func NewGetRepositoriesRepoNameSignaturesOK() *GetRepositoriesRepoNameSignaturesOK {
	return &GetRepositoriesRepoNameSignaturesOK{}
}

/*GetRepositoriesRepoNameSignaturesOK handles this case with default header values.

Retrieved signatures.
*/
type GetRepositoriesRepoNameSignaturesOK struct {
	Payload []*models.RepoSignature
}

func (o *GetRepositoriesRepoNameSignaturesOK) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/signatures][%d] getRepositoriesRepoNameSignaturesOK  %+v", 200, o.Payload)
}

func (o *GetRepositoriesRepoNameSignaturesOK) GetPayload() []*models.RepoSignature {
	return o.Payload
}

func (o *GetRepositoriesRepoNameSignaturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRepositoriesRepoNameSignaturesInternalServerError creates a GetRepositoriesRepoNameSignaturesInternalServerError with default headers values
func NewGetRepositoriesRepoNameSignaturesInternalServerError() *GetRepositoriesRepoNameSignaturesInternalServerError {
	return &GetRepositoriesRepoNameSignaturesInternalServerError{}
}

/*GetRepositoriesRepoNameSignaturesInternalServerError handles this case with default header values.

Server side error.
*/
type GetRepositoriesRepoNameSignaturesInternalServerError struct {
}

func (o *GetRepositoriesRepoNameSignaturesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/signatures][%d] getRepositoriesRepoNameSignaturesInternalServerError ", 500)
}

func (o *GetRepositoriesRepoNameSignaturesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
