// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoriesRepoNameTagsTagParams creates a new GetRepositoriesRepoNameTagsTagParams object
// with the default values initialized.
func NewGetRepositoriesRepoNameTagsTagParams() *GetRepositoriesRepoNameTagsTagParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagParamsWithTimeout creates a new GetRepositoriesRepoNameTagsTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesRepoNameTagsTagParamsWithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagParamsWithContext creates a new GetRepositoriesRepoNameTagsTagParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesRepoNameTagsTagParamsWithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagParams{

		Context: ctx,
	}
}

// NewGetRepositoriesRepoNameTagsTagParamsWithHTTPClient creates a new GetRepositoriesRepoNameTagsTagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesRepoNameTagsTagParamsWithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesRepoNameTagsTagParams contains all the parameters to send to the API endpoint
for the get repositories repo name tags tag operation typically these are written to a http.Request
*/
type GetRepositoriesRepoNameTagsTagParams struct {

	/*RepoName
	  Relevant repository name.

	*/
	RepoName string
	/*Tag
	  Tag of the repository.

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) WithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) WithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) WithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoName adds the repoName to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) WithRepoName(repoName string) *GetRepositoriesRepoNameTagsTagParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) WithTag(tag string) *GetRepositoriesRepoNameTagsTagParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get repositories repo name tags tag params
func (o *GetRepositoriesRepoNameTagsTagParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesRepoNameTagsTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
