// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLabelsIDResourcesParams creates a new GetLabelsIDResourcesParams object
// with the default values initialized.
func NewGetLabelsIDResourcesParams() *GetLabelsIDResourcesParams {
	var ()
	return &GetLabelsIDResourcesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLabelsIDResourcesParamsWithTimeout creates a new GetLabelsIDResourcesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLabelsIDResourcesParamsWithTimeout(timeout time.Duration) *GetLabelsIDResourcesParams {
	var ()
	return &GetLabelsIDResourcesParams{

		timeout: timeout,
	}
}

// NewGetLabelsIDResourcesParamsWithContext creates a new GetLabelsIDResourcesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLabelsIDResourcesParamsWithContext(ctx context.Context) *GetLabelsIDResourcesParams {
	var ()
	return &GetLabelsIDResourcesParams{

		Context: ctx,
	}
}

// NewGetLabelsIDResourcesParamsWithHTTPClient creates a new GetLabelsIDResourcesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLabelsIDResourcesParamsWithHTTPClient(client *http.Client) *GetLabelsIDResourcesParams {
	var ()
	return &GetLabelsIDResourcesParams{
		HTTPClient: client,
	}
}

/*GetLabelsIDResourcesParams contains all the parameters to send to the API endpoint
for the get labels ID resources operation typically these are written to a http.Request
*/
type GetLabelsIDResourcesParams struct {

	/*ID
	  Label ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) WithTimeout(timeout time.Duration) *GetLabelsIDResourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) WithContext(ctx context.Context) *GetLabelsIDResourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) WithHTTPClient(client *http.Client) *GetLabelsIDResourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) WithID(id int64) *GetLabelsIDResourcesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get labels ID resources params
func (o *GetLabelsIDResourcesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLabelsIDResourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
