// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoriesRepoNameTagsTagLabelsParams creates a new GetRepositoriesRepoNameTagsTagLabelsParams object
// with the default values initialized.
func NewGetRepositoriesRepoNameTagsTagLabelsParams() *GetRepositoriesRepoNameTagsTagLabelsParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagLabelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagLabelsParamsWithTimeout creates a new GetRepositoriesRepoNameTagsTagLabelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesRepoNameTagsTagLabelsParamsWithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagLabelsParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagLabelsParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagLabelsParamsWithContext creates a new GetRepositoriesRepoNameTagsTagLabelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesRepoNameTagsTagLabelsParamsWithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagLabelsParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagLabelsParams{

		Context: ctx,
	}
}

// NewGetRepositoriesRepoNameTagsTagLabelsParamsWithHTTPClient creates a new GetRepositoriesRepoNameTagsTagLabelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesRepoNameTagsTagLabelsParamsWithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagLabelsParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagLabelsParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesRepoNameTagsTagLabelsParams contains all the parameters to send to the API endpoint
for the get repositories repo name tags tag labels operation typically these are written to a http.Request
*/
type GetRepositoriesRepoNameTagsTagLabelsParams struct {

	/*RepoName
	  The name of repository.

	*/
	RepoName string
	/*Tag
	  The tag of the image.

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) WithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagLabelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) WithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagLabelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) WithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagLabelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoName adds the repoName to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) WithRepoName(repoName string) *GetRepositoriesRepoNameTagsTagLabelsParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) WithTag(tag string) *GetRepositoriesRepoNameTagsTagLabelsParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get repositories repo name tags tag labels params
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesRepoNameTagsTagLabelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
