// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoriesRepoNameTagsTagManifestParams creates a new GetRepositoriesRepoNameTagsTagManifestParams object
// with the default values initialized.
func NewGetRepositoriesRepoNameTagsTagManifestParams() *GetRepositoriesRepoNameTagsTagManifestParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagManifestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagManifestParamsWithTimeout creates a new GetRepositoriesRepoNameTagsTagManifestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesRepoNameTagsTagManifestParamsWithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagManifestParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagManifestParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagManifestParamsWithContext creates a new GetRepositoriesRepoNameTagsTagManifestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesRepoNameTagsTagManifestParamsWithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagManifestParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagManifestParams{

		Context: ctx,
	}
}

// NewGetRepositoriesRepoNameTagsTagManifestParamsWithHTTPClient creates a new GetRepositoriesRepoNameTagsTagManifestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesRepoNameTagsTagManifestParamsWithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagManifestParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagManifestParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesRepoNameTagsTagManifestParams contains all the parameters to send to the API endpoint
for the get repositories repo name tags tag manifest operation typically these are written to a http.Request
*/
type GetRepositoriesRepoNameTagsTagManifestParams struct {

	/*RepoName
	  Repository name

	*/
	RepoName string
	/*Tag
	  Tag name

	*/
	Tag string
	/*Version
	  The version of manifest, valid value are "v1" and "v2", default is "v2"

	*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagManifestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagManifestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagManifestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoName adds the repoName to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WithRepoName(repoName string) *GetRepositoriesRepoNameTagsTagManifestParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WithTag(tag string) *GetRepositoriesRepoNameTagsTagManifestParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) SetTag(tag string) {
	o.Tag = tag
}

// WithVersion adds the version to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WithVersion(version *string) *GetRepositoriesRepoNameTagsTagManifestParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get repositories repo name tags tag manifest params
func (o *GetRepositoriesRepoNameTagsTagManifestParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesRepoNameTagsTagManifestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if o.Version != nil {

		// query param version
		var qrVersion string
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
