// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sandhose/terraform-provider-harbor/api/models"
)

// GetRepositoriesRepoNameTagsTagManifestReader is a Reader for the GetRepositoriesRepoNameTagsTagManifest structure.
type GetRepositoriesRepoNameTagsTagManifestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesRepoNameTagsTagManifestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepositoriesRepoNameTagsTagManifestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetRepositoriesRepoNameTagsTagManifestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetRepositoriesRepoNameTagsTagManifestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRepositoriesRepoNameTagsTagManifestOK creates a GetRepositoriesRepoNameTagsTagManifestOK with default headers values
func NewGetRepositoriesRepoNameTagsTagManifestOK() *GetRepositoriesRepoNameTagsTagManifestOK {
	return &GetRepositoriesRepoNameTagsTagManifestOK{}
}

/*GetRepositoriesRepoNameTagsTagManifestOK handles this case with default header values.

Retrieved manifests from a relevant repository successfully.
*/
type GetRepositoriesRepoNameTagsTagManifestOK struct {
	Payload *models.Manifest
}

func (o *GetRepositoriesRepoNameTagsTagManifestOK) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/manifest][%d] getRepositoriesRepoNameTagsTagManifestOK  %+v", 200, o.Payload)
}

func (o *GetRepositoriesRepoNameTagsTagManifestOK) GetPayload() *models.Manifest {
	return o.Payload
}

func (o *GetRepositoriesRepoNameTagsTagManifestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Manifest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRepositoriesRepoNameTagsTagManifestNotFound creates a GetRepositoriesRepoNameTagsTagManifestNotFound with default headers values
func NewGetRepositoriesRepoNameTagsTagManifestNotFound() *GetRepositoriesRepoNameTagsTagManifestNotFound {
	return &GetRepositoriesRepoNameTagsTagManifestNotFound{}
}

/*GetRepositoriesRepoNameTagsTagManifestNotFound handles this case with default header values.

Retrieved manifests from a relevant repository not found.
*/
type GetRepositoriesRepoNameTagsTagManifestNotFound struct {
}

func (o *GetRepositoriesRepoNameTagsTagManifestNotFound) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/manifest][%d] getRepositoriesRepoNameTagsTagManifestNotFound ", 404)
}

func (o *GetRepositoriesRepoNameTagsTagManifestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRepositoriesRepoNameTagsTagManifestInternalServerError creates a GetRepositoriesRepoNameTagsTagManifestInternalServerError with default headers values
func NewGetRepositoriesRepoNameTagsTagManifestInternalServerError() *GetRepositoriesRepoNameTagsTagManifestInternalServerError {
	return &GetRepositoriesRepoNameTagsTagManifestInternalServerError{}
}

/*GetRepositoriesRepoNameTagsTagManifestInternalServerError handles this case with default header values.

Unexpected internal errors.
*/
type GetRepositoriesRepoNameTagsTagManifestInternalServerError struct {
}

func (o *GetRepositoriesRepoNameTagsTagManifestInternalServerError) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/manifest][%d] getRepositoriesRepoNameTagsTagManifestInternalServerError ", 500)
}

func (o *GetRepositoriesRepoNameTagsTagManifestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
