// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/sandhose/terraform-provider-harbor/api/models"
)

// GetRepositoriesRepoNameTagsTagLabelsReader is a Reader for the GetRepositoriesRepoNameTagsTagLabels structure.
type GetRepositoriesRepoNameTagsTagLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRepositoriesRepoNameTagsTagLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRepositoriesRepoNameTagsTagLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetRepositoriesRepoNameTagsTagLabelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetRepositoriesRepoNameTagsTagLabelsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRepositoriesRepoNameTagsTagLabelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRepositoriesRepoNameTagsTagLabelsOK creates a GetRepositoriesRepoNameTagsTagLabelsOK with default headers values
func NewGetRepositoriesRepoNameTagsTagLabelsOK() *GetRepositoriesRepoNameTagsTagLabelsOK {
	return &GetRepositoriesRepoNameTagsTagLabelsOK{}
}

/*GetRepositoriesRepoNameTagsTagLabelsOK handles this case with default header values.

Successfully.
*/
type GetRepositoriesRepoNameTagsTagLabelsOK struct {
	Payload []*models.Label
}

func (o *GetRepositoriesRepoNameTagsTagLabelsOK) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/labels][%d] getRepositoriesRepoNameTagsTagLabelsOK  %+v", 200, o.Payload)
}

func (o *GetRepositoriesRepoNameTagsTagLabelsOK) GetPayload() []*models.Label {
	return o.Payload
}

func (o *GetRepositoriesRepoNameTagsTagLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRepositoriesRepoNameTagsTagLabelsUnauthorized creates a GetRepositoriesRepoNameTagsTagLabelsUnauthorized with default headers values
func NewGetRepositoriesRepoNameTagsTagLabelsUnauthorized() *GetRepositoriesRepoNameTagsTagLabelsUnauthorized {
	return &GetRepositoriesRepoNameTagsTagLabelsUnauthorized{}
}

/*GetRepositoriesRepoNameTagsTagLabelsUnauthorized handles this case with default header values.

Unauthorized.
*/
type GetRepositoriesRepoNameTagsTagLabelsUnauthorized struct {
}

func (o *GetRepositoriesRepoNameTagsTagLabelsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/labels][%d] getRepositoriesRepoNameTagsTagLabelsUnauthorized ", 401)
}

func (o *GetRepositoriesRepoNameTagsTagLabelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRepositoriesRepoNameTagsTagLabelsForbidden creates a GetRepositoriesRepoNameTagsTagLabelsForbidden with default headers values
func NewGetRepositoriesRepoNameTagsTagLabelsForbidden() *GetRepositoriesRepoNameTagsTagLabelsForbidden {
	return &GetRepositoriesRepoNameTagsTagLabelsForbidden{}
}

/*GetRepositoriesRepoNameTagsTagLabelsForbidden handles this case with default header values.

Forbidden. User should have read permisson for the image to perform the action.
*/
type GetRepositoriesRepoNameTagsTagLabelsForbidden struct {
}

func (o *GetRepositoriesRepoNameTagsTagLabelsForbidden) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/labels][%d] getRepositoriesRepoNameTagsTagLabelsForbidden ", 403)
}

func (o *GetRepositoriesRepoNameTagsTagLabelsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRepositoriesRepoNameTagsTagLabelsNotFound creates a GetRepositoriesRepoNameTagsTagLabelsNotFound with default headers values
func NewGetRepositoriesRepoNameTagsTagLabelsNotFound() *GetRepositoriesRepoNameTagsTagLabelsNotFound {
	return &GetRepositoriesRepoNameTagsTagLabelsNotFound{}
}

/*GetRepositoriesRepoNameTagsTagLabelsNotFound handles this case with default header values.

Resource not found.
*/
type GetRepositoriesRepoNameTagsTagLabelsNotFound struct {
}

func (o *GetRepositoriesRepoNameTagsTagLabelsNotFound) Error() string {
	return fmt.Sprintf("[GET /repositories/{repo_name}/tags/{tag}/labels][%d] getRepositoriesRepoNameTagsTagLabelsNotFound ", 404)
}

func (o *GetRepositoriesRepoNameTagsTagLabelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
