// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoriesRepoNameTagsTagScanUUIDLogParams creates a new GetRepositoriesRepoNameTagsTagScanUUIDLogParams object
// with the default values initialized.
func NewGetRepositoriesRepoNameTagsTagScanUUIDLogParams() *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanUUIDLogParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagScanUUIDLogParamsWithTimeout creates a new GetRepositoriesRepoNameTagsTagScanUUIDLogParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesRepoNameTagsTagScanUUIDLogParamsWithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanUUIDLogParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagScanUUIDLogParamsWithContext creates a new GetRepositoriesRepoNameTagsTagScanUUIDLogParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesRepoNameTagsTagScanUUIDLogParamsWithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanUUIDLogParams{

		Context: ctx,
	}
}

// NewGetRepositoriesRepoNameTagsTagScanUUIDLogParamsWithHTTPClient creates a new GetRepositoriesRepoNameTagsTagScanUUIDLogParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesRepoNameTagsTagScanUUIDLogParamsWithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanUUIDLogParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesRepoNameTagsTagScanUUIDLogParams contains all the parameters to send to the API endpoint
for the get repositories repo name tags tag scan UUID log operation typically these are written to a http.Request
*/
type GetRepositoriesRepoNameTagsTagScanUUIDLogParams struct {

	/*RepoName
	  Repository name

	*/
	RepoName string
	/*Tag
	  Tag name

	*/
	Tag string
	/*UUID
	  the scan unique identifier

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoName adds the repoName to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WithRepoName(repoName string) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WithTag(tag string) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) SetTag(tag string) {
	o.Tag = tag
}

// WithUUID adds the uuid to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WithUUID(uuid string) *GetRepositoriesRepoNameTagsTagScanUUIDLogParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the get repositories repo name tags tag scan UUID log params
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesRepoNameTagsTagScanUUIDLogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
