// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostRepositoriesRepoNameTagsTagScanReader is a Reader for the PostRepositoriesRepoNameTagsTagScan structure.
type PostRepositoriesRepoNameTagsTagScanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRepositoriesRepoNameTagsTagScanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPostRepositoriesRepoNameTagsTagScanAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostRepositoriesRepoNameTagsTagScanUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostRepositoriesRepoNameTagsTagScanForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostRepositoriesRepoNameTagsTagScanNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostRepositoriesRepoNameTagsTagScanInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRepositoriesRepoNameTagsTagScanAccepted creates a PostRepositoriesRepoNameTagsTagScanAccepted with default headers values
func NewPostRepositoriesRepoNameTagsTagScanAccepted() *PostRepositoriesRepoNameTagsTagScanAccepted {
	return &PostRepositoriesRepoNameTagsTagScanAccepted{}
}

/*PostRepositoriesRepoNameTagsTagScanAccepted handles this case with default header values.

Scan request is successfully accepted
*/
type PostRepositoriesRepoNameTagsTagScanAccepted struct {
}

func (o *PostRepositoriesRepoNameTagsTagScanAccepted) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/scan][%d] postRepositoriesRepoNameTagsTagScanAccepted ", 202)
}

func (o *PostRepositoriesRepoNameTagsTagScanAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagScanUnauthorized creates a PostRepositoriesRepoNameTagsTagScanUnauthorized with default headers values
func NewPostRepositoriesRepoNameTagsTagScanUnauthorized() *PostRepositoriesRepoNameTagsTagScanUnauthorized {
	return &PostRepositoriesRepoNameTagsTagScanUnauthorized{}
}

/*PostRepositoriesRepoNameTagsTagScanUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRepositoriesRepoNameTagsTagScanUnauthorized struct {
}

func (o *PostRepositoriesRepoNameTagsTagScanUnauthorized) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/scan][%d] postRepositoriesRepoNameTagsTagScanUnauthorized ", 401)
}

func (o *PostRepositoriesRepoNameTagsTagScanUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagScanForbidden creates a PostRepositoriesRepoNameTagsTagScanForbidden with default headers values
func NewPostRepositoriesRepoNameTagsTagScanForbidden() *PostRepositoriesRepoNameTagsTagScanForbidden {
	return &PostRepositoriesRepoNameTagsTagScanForbidden{}
}

/*PostRepositoriesRepoNameTagsTagScanForbidden handles this case with default header values.

Request is not allowed
*/
type PostRepositoriesRepoNameTagsTagScanForbidden struct {
}

func (o *PostRepositoriesRepoNameTagsTagScanForbidden) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/scan][%d] postRepositoriesRepoNameTagsTagScanForbidden ", 403)
}

func (o *PostRepositoriesRepoNameTagsTagScanForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagScanNotFound creates a PostRepositoriesRepoNameTagsTagScanNotFound with default headers values
func NewPostRepositoriesRepoNameTagsTagScanNotFound() *PostRepositoriesRepoNameTagsTagScanNotFound {
	return &PostRepositoriesRepoNameTagsTagScanNotFound{}
}

/*PostRepositoriesRepoNameTagsTagScanNotFound handles this case with default header values.

The target artifact is not found
*/
type PostRepositoriesRepoNameTagsTagScanNotFound struct {
}

func (o *PostRepositoriesRepoNameTagsTagScanNotFound) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/scan][%d] postRepositoriesRepoNameTagsTagScanNotFound ", 404)
}

func (o *PostRepositoriesRepoNameTagsTagScanNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagScanInternalServerError creates a PostRepositoriesRepoNameTagsTagScanInternalServerError with default headers values
func NewPostRepositoriesRepoNameTagsTagScanInternalServerError() *PostRepositoriesRepoNameTagsTagScanInternalServerError {
	return &PostRepositoriesRepoNameTagsTagScanInternalServerError{}
}

/*PostRepositoriesRepoNameTagsTagScanInternalServerError handles this case with default header values.

Internal server error happened
*/
type PostRepositoriesRepoNameTagsTagScanInternalServerError struct {
}

func (o *PostRepositoriesRepoNameTagsTagScanInternalServerError) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/scan][%d] postRepositoriesRepoNameTagsTagScanInternalServerError ", 500)
}

func (o *PostRepositoriesRepoNameTagsTagScanInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
