// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRepositoriesRepoNameTagsTagScanParams creates a new PostRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized.
func NewPostRepositoriesRepoNameTagsTagScanParams() *PostRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &PostRepositoriesRepoNameTagsTagScanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRepositoriesRepoNameTagsTagScanParamsWithTimeout creates a new PostRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRepositoriesRepoNameTagsTagScanParamsWithTimeout(timeout time.Duration) *PostRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &PostRepositoriesRepoNameTagsTagScanParams{

		timeout: timeout,
	}
}

// NewPostRepositoriesRepoNameTagsTagScanParamsWithContext creates a new PostRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRepositoriesRepoNameTagsTagScanParamsWithContext(ctx context.Context) *PostRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &PostRepositoriesRepoNameTagsTagScanParams{

		Context: ctx,
	}
}

// NewPostRepositoriesRepoNameTagsTagScanParamsWithHTTPClient creates a new PostRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostRepositoriesRepoNameTagsTagScanParamsWithHTTPClient(client *http.Client) *PostRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &PostRepositoriesRepoNameTagsTagScanParams{
		HTTPClient: client,
	}
}

/*PostRepositoriesRepoNameTagsTagScanParams contains all the parameters to send to the API endpoint
for the post repositories repo name tags tag scan operation typically these are written to a http.Request
*/
type PostRepositoriesRepoNameTagsTagScanParams struct {

	/*RepoName
	  Repository name

	*/
	RepoName string
	/*Tag
	  Tag name

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) WithTimeout(timeout time.Duration) *PostRepositoriesRepoNameTagsTagScanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) WithContext(ctx context.Context) *PostRepositoriesRepoNameTagsTagScanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) WithHTTPClient(client *http.Client) *PostRepositoriesRepoNameTagsTagScanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepoName adds the repoName to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) WithRepoName(repoName string) *PostRepositoriesRepoNameTagsTagScanParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) WithTag(tag string) *PostRepositoriesRepoNameTagsTagScanParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the post repositories repo name tags tag scan params
func (o *PostRepositoriesRepoNameTagsTagScanParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *PostRepositoriesRepoNameTagsTagScanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
