// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// PostUsersUserIDGenCliSecretReader is a Reader for the PostUsersUserIDGenCliSecret structure.
type PostUsersUserIDGenCliSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUsersUserIDGenCliSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostUsersUserIDGenCliSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostUsersUserIDGenCliSecretBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPostUsersUserIDGenCliSecretUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostUsersUserIDGenCliSecretForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostUsersUserIDGenCliSecretNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 412:
		result := NewPostUsersUserIDGenCliSecretPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostUsersUserIDGenCliSecretInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUsersUserIDGenCliSecretOK creates a PostUsersUserIDGenCliSecretOK with default headers values
func NewPostUsersUserIDGenCliSecretOK() *PostUsersUserIDGenCliSecretOK {
	return &PostUsersUserIDGenCliSecretOK{}
}

/*PostUsersUserIDGenCliSecretOK handles this case with default header values.

The secret is successfully generated.
*/
type PostUsersUserIDGenCliSecretOK struct {
	Payload *PostUsersUserIDGenCliSecretOKBody
}

func (o *PostUsersUserIDGenCliSecretOK) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretOK  %+v", 200, o.Payload)
}

func (o *PostUsersUserIDGenCliSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostUsersUserIDGenCliSecretOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUsersUserIDGenCliSecretBadRequest creates a PostUsersUserIDGenCliSecretBadRequest with default headers values
func NewPostUsersUserIDGenCliSecretBadRequest() *PostUsersUserIDGenCliSecretBadRequest {
	return &PostUsersUserIDGenCliSecretBadRequest{}
}

/*PostUsersUserIDGenCliSecretBadRequest handles this case with default header values.

Invalid user ID.  Or user is not onboarded via OIDC authentication.
*/
type PostUsersUserIDGenCliSecretBadRequest struct {
}

func (o *PostUsersUserIDGenCliSecretBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretBadRequest ", 400)
}

func (o *PostUsersUserIDGenCliSecretBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersUserIDGenCliSecretUnauthorized creates a PostUsersUserIDGenCliSecretUnauthorized with default headers values
func NewPostUsersUserIDGenCliSecretUnauthorized() *PostUsersUserIDGenCliSecretUnauthorized {
	return &PostUsersUserIDGenCliSecretUnauthorized{}
}

/*PostUsersUserIDGenCliSecretUnauthorized handles this case with default header values.

User need to log in first.
*/
type PostUsersUserIDGenCliSecretUnauthorized struct {
}

func (o *PostUsersUserIDGenCliSecretUnauthorized) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretUnauthorized ", 401)
}

func (o *PostUsersUserIDGenCliSecretUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersUserIDGenCliSecretForbidden creates a PostUsersUserIDGenCliSecretForbidden with default headers values
func NewPostUsersUserIDGenCliSecretForbidden() *PostUsersUserIDGenCliSecretForbidden {
	return &PostUsersUserIDGenCliSecretForbidden{}
}

/*PostUsersUserIDGenCliSecretForbidden handles this case with default header values.

Non-admin user can only generate the cli secret of himself.
*/
type PostUsersUserIDGenCliSecretForbidden struct {
}

func (o *PostUsersUserIDGenCliSecretForbidden) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretForbidden ", 403)
}

func (o *PostUsersUserIDGenCliSecretForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersUserIDGenCliSecretNotFound creates a PostUsersUserIDGenCliSecretNotFound with default headers values
func NewPostUsersUserIDGenCliSecretNotFound() *PostUsersUserIDGenCliSecretNotFound {
	return &PostUsersUserIDGenCliSecretNotFound{}
}

/*PostUsersUserIDGenCliSecretNotFound handles this case with default header values.

User ID does not exist.
*/
type PostUsersUserIDGenCliSecretNotFound struct {
}

func (o *PostUsersUserIDGenCliSecretNotFound) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretNotFound ", 404)
}

func (o *PostUsersUserIDGenCliSecretNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersUserIDGenCliSecretPreconditionFailed creates a PostUsersUserIDGenCliSecretPreconditionFailed with default headers values
func NewPostUsersUserIDGenCliSecretPreconditionFailed() *PostUsersUserIDGenCliSecretPreconditionFailed {
	return &PostUsersUserIDGenCliSecretPreconditionFailed{}
}

/*PostUsersUserIDGenCliSecretPreconditionFailed handles this case with default header values.

The auth mode of the system is not "oidc_auth", or the user is not onboarded via OIDC AuthN.
*/
type PostUsersUserIDGenCliSecretPreconditionFailed struct {
}

func (o *PostUsersUserIDGenCliSecretPreconditionFailed) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretPreconditionFailed ", 412)
}

func (o *PostUsersUserIDGenCliSecretPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostUsersUserIDGenCliSecretInternalServerError creates a PostUsersUserIDGenCliSecretInternalServerError with default headers values
func NewPostUsersUserIDGenCliSecretInternalServerError() *PostUsersUserIDGenCliSecretInternalServerError {
	return &PostUsersUserIDGenCliSecretInternalServerError{}
}

/*PostUsersUserIDGenCliSecretInternalServerError handles this case with default header values.

Unexpected internal errors.
*/
type PostUsersUserIDGenCliSecretInternalServerError struct {
}

func (o *PostUsersUserIDGenCliSecretInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users/{user_id}/gen_cli_secret][%d] postUsersUserIdGenCliSecretInternalServerError ", 500)
}

func (o *PostUsersUserIDGenCliSecretInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostUsersUserIDGenCliSecretOKBody post users user ID gen cli secret o k body
swagger:model PostUsersUserIDGenCliSecretOKBody
*/
type PostUsersUserIDGenCliSecretOKBody struct {

	// The new secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this post users user ID gen cli secret o k body
func (o *PostUsersUserIDGenCliSecretOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostUsersUserIDGenCliSecretOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostUsersUserIDGenCliSecretOKBody) UnmarshalBinary(b []byte) error {
	var res PostUsersUserIDGenCliSecretOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
