// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostInternalSyncregistryParams creates a new PostInternalSyncregistryParams object
// with the default values initialized.
func NewPostInternalSyncregistryParams() *PostInternalSyncregistryParams {

	return &PostInternalSyncregistryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostInternalSyncregistryParamsWithTimeout creates a new PostInternalSyncregistryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostInternalSyncregistryParamsWithTimeout(timeout time.Duration) *PostInternalSyncregistryParams {

	return &PostInternalSyncregistryParams{

		timeout: timeout,
	}
}

// NewPostInternalSyncregistryParamsWithContext creates a new PostInternalSyncregistryParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostInternalSyncregistryParamsWithContext(ctx context.Context) *PostInternalSyncregistryParams {

	return &PostInternalSyncregistryParams{

		Context: ctx,
	}
}

// NewPostInternalSyncregistryParamsWithHTTPClient creates a new PostInternalSyncregistryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostInternalSyncregistryParamsWithHTTPClient(client *http.Client) *PostInternalSyncregistryParams {

	return &PostInternalSyncregistryParams{
		HTTPClient: client,
	}
}

/*PostInternalSyncregistryParams contains all the parameters to send to the API endpoint
for the post internal syncregistry operation typically these are written to a http.Request
*/
type PostInternalSyncregistryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post internal syncregistry params
func (o *PostInternalSyncregistryParams) WithTimeout(timeout time.Duration) *PostInternalSyncregistryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post internal syncregistry params
func (o *PostInternalSyncregistryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post internal syncregistry params
func (o *PostInternalSyncregistryParams) WithContext(ctx context.Context) *PostInternalSyncregistryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post internal syncregistry params
func (o *PostInternalSyncregistryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post internal syncregistry params
func (o *PostInternalSyncregistryParams) WithHTTPClient(client *http.Client) *PostInternalSyncregistryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post internal syncregistry params
func (o *PostInternalSyncregistryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostInternalSyncregistryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
