// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostRepositoriesRepoNameTagsTagLabelsReader is a Reader for the PostRepositoriesRepoNameTagsTagLabels structure.
type PostRepositoriesRepoNameTagsTagLabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRepositoriesRepoNameTagsTagLabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRepositoriesRepoNameTagsTagLabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostRepositoriesRepoNameTagsTagLabelsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostRepositoriesRepoNameTagsTagLabelsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostRepositoriesRepoNameTagsTagLabelsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRepositoriesRepoNameTagsTagLabelsOK creates a PostRepositoriesRepoNameTagsTagLabelsOK with default headers values
func NewPostRepositoriesRepoNameTagsTagLabelsOK() *PostRepositoriesRepoNameTagsTagLabelsOK {
	return &PostRepositoriesRepoNameTagsTagLabelsOK{}
}

/*PostRepositoriesRepoNameTagsTagLabelsOK handles this case with default header values.

Successfully.
*/
type PostRepositoriesRepoNameTagsTagLabelsOK struct {
}

func (o *PostRepositoriesRepoNameTagsTagLabelsOK) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/labels][%d] postRepositoriesRepoNameTagsTagLabelsOK ", 200)
}

func (o *PostRepositoriesRepoNameTagsTagLabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagLabelsUnauthorized creates a PostRepositoriesRepoNameTagsTagLabelsUnauthorized with default headers values
func NewPostRepositoriesRepoNameTagsTagLabelsUnauthorized() *PostRepositoriesRepoNameTagsTagLabelsUnauthorized {
	return &PostRepositoriesRepoNameTagsTagLabelsUnauthorized{}
}

/*PostRepositoriesRepoNameTagsTagLabelsUnauthorized handles this case with default header values.

Unauthorized.
*/
type PostRepositoriesRepoNameTagsTagLabelsUnauthorized struct {
}

func (o *PostRepositoriesRepoNameTagsTagLabelsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/labels][%d] postRepositoriesRepoNameTagsTagLabelsUnauthorized ", 401)
}

func (o *PostRepositoriesRepoNameTagsTagLabelsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagLabelsForbidden creates a PostRepositoriesRepoNameTagsTagLabelsForbidden with default headers values
func NewPostRepositoriesRepoNameTagsTagLabelsForbidden() *PostRepositoriesRepoNameTagsTagLabelsForbidden {
	return &PostRepositoriesRepoNameTagsTagLabelsForbidden{}
}

/*PostRepositoriesRepoNameTagsTagLabelsForbidden handles this case with default header values.

Forbidden. User should have write permisson for the image to perform the action.
*/
type PostRepositoriesRepoNameTagsTagLabelsForbidden struct {
}

func (o *PostRepositoriesRepoNameTagsTagLabelsForbidden) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/labels][%d] postRepositoriesRepoNameTagsTagLabelsForbidden ", 403)
}

func (o *PostRepositoriesRepoNameTagsTagLabelsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostRepositoriesRepoNameTagsTagLabelsNotFound creates a PostRepositoriesRepoNameTagsTagLabelsNotFound with default headers values
func NewPostRepositoriesRepoNameTagsTagLabelsNotFound() *PostRepositoriesRepoNameTagsTagLabelsNotFound {
	return &PostRepositoriesRepoNameTagsTagLabelsNotFound{}
}

/*PostRepositoriesRepoNameTagsTagLabelsNotFound handles this case with default header values.

Resource not found.
*/
type PostRepositoriesRepoNameTagsTagLabelsNotFound struct {
}

func (o *PostRepositoriesRepoNameTagsTagLabelsNotFound) Error() string {
	return fmt.Sprintf("[POST /repositories/{repo_name}/tags/{tag}/labels][%d] postRepositoriesRepoNameTagsTagLabelsNotFound ", 404)
}

func (o *PostRepositoriesRepoNameTagsTagLabelsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
