// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostInternalSyncregistryReader is a Reader for the PostInternalSyncregistry structure.
type PostInternalSyncregistryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInternalSyncregistryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostInternalSyncregistryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostInternalSyncregistryUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPostInternalSyncregistryForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 415:
		result := NewPostInternalSyncregistryUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostInternalSyncregistryInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostInternalSyncregistryOK creates a PostInternalSyncregistryOK with default headers values
func NewPostInternalSyncregistryOK() *PostInternalSyncregistryOK {
	return &PostInternalSyncregistryOK{}
}

/*PostInternalSyncregistryOK handles this case with default header values.

Sync repositories successfully.
*/
type PostInternalSyncregistryOK struct {
}

func (o *PostInternalSyncregistryOK) Error() string {
	return fmt.Sprintf("[POST /internal/syncregistry][%d] postInternalSyncregistryOK ", 200)
}

func (o *PostInternalSyncregistryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalSyncregistryUnauthorized creates a PostInternalSyncregistryUnauthorized with default headers values
func NewPostInternalSyncregistryUnauthorized() *PostInternalSyncregistryUnauthorized {
	return &PostInternalSyncregistryUnauthorized{}
}

/*PostInternalSyncregistryUnauthorized handles this case with default header values.

User need to log in first.
*/
type PostInternalSyncregistryUnauthorized struct {
}

func (o *PostInternalSyncregistryUnauthorized) Error() string {
	return fmt.Sprintf("[POST /internal/syncregistry][%d] postInternalSyncregistryUnauthorized ", 401)
}

func (o *PostInternalSyncregistryUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalSyncregistryForbidden creates a PostInternalSyncregistryForbidden with default headers values
func NewPostInternalSyncregistryForbidden() *PostInternalSyncregistryForbidden {
	return &PostInternalSyncregistryForbidden{}
}

/*PostInternalSyncregistryForbidden handles this case with default header values.

User does not have permission of admin role.
*/
type PostInternalSyncregistryForbidden struct {
}

func (o *PostInternalSyncregistryForbidden) Error() string {
	return fmt.Sprintf("[POST /internal/syncregistry][%d] postInternalSyncregistryForbidden ", 403)
}

func (o *PostInternalSyncregistryForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalSyncregistryUnsupportedMediaType creates a PostInternalSyncregistryUnsupportedMediaType with default headers values
func NewPostInternalSyncregistryUnsupportedMediaType() *PostInternalSyncregistryUnsupportedMediaType {
	return &PostInternalSyncregistryUnsupportedMediaType{}
}

/*PostInternalSyncregistryUnsupportedMediaType handles this case with default header values.

The Media Type of the request is not supported, it has to be "application/json"
*/
type PostInternalSyncregistryUnsupportedMediaType struct {
}

func (o *PostInternalSyncregistryUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /internal/syncregistry][%d] postInternalSyncregistryUnsupportedMediaType ", 415)
}

func (o *PostInternalSyncregistryUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalSyncregistryInternalServerError creates a PostInternalSyncregistryInternalServerError with default headers values
func NewPostInternalSyncregistryInternalServerError() *PostInternalSyncregistryInternalServerError {
	return &PostInternalSyncregistryInternalServerError{}
}

/*PostInternalSyncregistryInternalServerError handles this case with default header values.

Unexpected internal errors.
*/
type PostInternalSyncregistryInternalServerError struct {
}

func (o *PostInternalSyncregistryInternalServerError) Error() string {
	return fmt.Sprintf("[POST /internal/syncregistry][%d] postInternalSyncregistryInternalServerError ", 500)
}

func (o *PostInternalSyncregistryInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
