// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostInternalSyncquotaReader is a Reader for the PostInternalSyncquota structure.
type PostInternalSyncquotaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInternalSyncquotaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostInternalSyncquotaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostInternalSyncquotaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostInternalSyncquotaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostInternalSyncquotaOK creates a PostInternalSyncquotaOK with default headers values
func NewPostInternalSyncquotaOK() *PostInternalSyncquotaOK {
	return &PostInternalSyncquotaOK{}
}

/*PostInternalSyncquotaOK handles this case with default header values.

Sync repositories successfully.
*/
type PostInternalSyncquotaOK struct {
}

func (o *PostInternalSyncquotaOK) Error() string {
	return fmt.Sprintf("[POST /internal/syncquota][%d] postInternalSyncquotaOK ", 200)
}

func (o *PostInternalSyncquotaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalSyncquotaUnauthorized creates a PostInternalSyncquotaUnauthorized with default headers values
func NewPostInternalSyncquotaUnauthorized() *PostInternalSyncquotaUnauthorized {
	return &PostInternalSyncquotaUnauthorized{}
}

/*PostInternalSyncquotaUnauthorized handles this case with default header values.

User need to log in first.
*/
type PostInternalSyncquotaUnauthorized struct {
}

func (o *PostInternalSyncquotaUnauthorized) Error() string {
	return fmt.Sprintf("[POST /internal/syncquota][%d] postInternalSyncquotaUnauthorized ", 401)
}

func (o *PostInternalSyncquotaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostInternalSyncquotaForbidden creates a PostInternalSyncquotaForbidden with default headers values
func NewPostInternalSyncquotaForbidden() *PostInternalSyncquotaForbidden {
	return &PostInternalSyncquotaForbidden{}
}

/*PostInternalSyncquotaForbidden handles this case with default header values.

User does not have permission of system admin role.
*/
type PostInternalSyncquotaForbidden struct {
}

func (o *PostInternalSyncquotaForbidden) Error() string {
	return fmt.Sprintf("[POST /internal/syncquota][%d] postInternalSyncquotaForbidden ", 403)
}

func (o *PostInternalSyncquotaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
