// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRepositoriesRepoNameTagsTagScanParams creates a new GetRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized.
func NewGetRepositoriesRepoNameTagsTagScanParams() *GetRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagScanParamsWithTimeout creates a new GetRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRepositoriesRepoNameTagsTagScanParamsWithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanParams{

		timeout: timeout,
	}
}

// NewGetRepositoriesRepoNameTagsTagScanParamsWithContext creates a new GetRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRepositoriesRepoNameTagsTagScanParamsWithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanParams{

		Context: ctx,
	}
}

// NewGetRepositoriesRepoNameTagsTagScanParamsWithHTTPClient creates a new GetRepositoriesRepoNameTagsTagScanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRepositoriesRepoNameTagsTagScanParamsWithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagScanParams {
	var ()
	return &GetRepositoriesRepoNameTagsTagScanParams{
		HTTPClient: client,
	}
}

/*GetRepositoriesRepoNameTagsTagScanParams contains all the parameters to send to the API endpoint
for the get repositories repo name tags tag scan operation typically these are written to a http.Request
*/
type GetRepositoriesRepoNameTagsTagScanParams struct {

	/*Accept
	  Mimetype in header. e.g: "application/vnd.scanner.adapter.vuln.report.harbor+json; version=1.0"


	*/
	Accept *string
	/*RepoName
	  Repository name

	*/
	RepoName string
	/*Tag
	  Tag name

	*/
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) WithTimeout(timeout time.Duration) *GetRepositoriesRepoNameTagsTagScanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) WithContext(ctx context.Context) *GetRepositoriesRepoNameTagsTagScanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) WithHTTPClient(client *http.Client) *GetRepositoriesRepoNameTagsTagScanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccept adds the accept to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) WithAccept(accept *string) *GetRepositoriesRepoNameTagsTagScanParams {
	o.SetAccept(accept)
	return o
}

// SetAccept adds the accept to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) SetAccept(accept *string) {
	o.Accept = accept
}

// WithRepoName adds the repoName to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) WithRepoName(repoName string) *GetRepositoriesRepoNameTagsTagScanParams {
	o.SetRepoName(repoName)
	return o
}

// SetRepoName adds the repoName to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) SetRepoName(repoName string) {
	o.RepoName = repoName
}

// WithTag adds the tag to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) WithTag(tag string) *GetRepositoriesRepoNameTagsTagScanParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get repositories repo name tags tag scan params
func (o *GetRepositoriesRepoNameTagsTagScanParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoriesRepoNameTagsTagScanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Accept != nil {

		// header param Accept
		if err := r.SetHeaderParam("Accept", *o.Accept); err != nil {
			return err
		}

	}

	// path param repo_name
	if err := r.SetPathParam("repo_name", o.RepoName); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
