// Code generated by go-swagger; DO NOT EDIT.

package scan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new scan API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for scan API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetRepositoriesRepoNameTagsTagScan(params *GetRepositoriesRepoNameTagsTagScanParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepositoriesRepoNameTagsTagScanOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetRepositoriesRepoNameTagsTagScan gets the scan report

  Retrieve the scan report for the artifact identified by the repo_name and tag.

*/
func (a *Client) GetRepositoriesRepoNameTagsTagScan(params *GetRepositoriesRepoNameTagsTagScanParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepositoriesRepoNameTagsTagScanOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRepositoriesRepoNameTagsTagScanParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetRepositoriesRepoNameTagsTagScan",
		Method:             "GET",
		PathPattern:        "/repositories/{repo_name}/tags/{tag}/scan",
		ProducesMediaTypes: []string{"application/json", "text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRepositoriesRepoNameTagsTagScanReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRepositoriesRepoNameTagsTagScanOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetRepositoriesRepoNameTagsTagScan: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
